require: rubocop-performance
require: rubocop-rspec
AllCops:
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'app/mailers/**/*'
    - 'app/jobs/**/*'
    - 'app/channels/**/*'
    - 'vendor/bundle/**/*'
Style/Documentation:
  Enabled: true
  Exclude:
        - 'app/models/application_record.rb'
        - 'app/controllers/**/*'
RSpec/MultipleExpectations:
  Enabled: true
  Max: 3
RSpec/NestedGroups:
  Enabled: false
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/MethodLength:
  Enabled: true
  Exclude:
    - 'app/controllers/graphql_controller.rb'
RSpec/ExampleLength:
  Max: 6
RSpec/MultipleExpectations:
  Max: 6
Lint/UnreachableCode:
  Enabled: true
  Exclude:
        - 'app/concepts/api/v1/auth/operation/sign_in.rb'
Metrics/AbcSize:
  Enabled: true
  Exclude:
      - 'app/controllers/api/v1/api_controller.rb'
Style/SignalException:
  Enabled: true
  Exclude:
        - 'app/concepts/api/v1/auth/operation/sign_in.rb'
