require: rubocop-performance
require: rubocop-rspec
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'app/mailers/**/*'
    - 'app/jobs/**/*'
    - 'app/channels/**/*'
Style/Documentation:
  Enabled: true
  Exclude:
        - 'app/models/application_record.rb'
