require: rubocop-performance
require: rubocop-rspec
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'app/mailers/**/*'
    - 'app/jobs/**/*'
    - 'app/channels/**/*'
Style/Documentation:
  Enabled: true
  Exclude:
        - 'app/models/application_record.rb'
        - 'app/controllers/**/*'
RSpec/MultipleExpectations:
  Enabled: true
  Max: 3
RSpec/NestedGroups:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
